sudo: false
cache:
  directories:
    - $HOME/.cache/pip

language: python


matrix:
  include:
    - python: "2.6"  # these are just to make travis's UI a bit prettier
      env: TOXENV=py26
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.3"
      env: TOXENV=py33
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35


install:
  - pip install tox


script:
  - tox


notifications:
  email: false
